name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate changelog
      id: changelog
      run: |
        # Get the previous tag
        PREV_TAG=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || echo "")

        # Generate changelog
        if [ -n "$PREV_TAG" ]; then
          CHANGELOG=$(git log ${PREV_TAG}..HEAD --oneline --pretty=format:"- %s")
        else
          CHANGELOG=$(git log --oneline --pretty=format:"- %s")
        fi

        # Save changelog to file
        cat > CHANGELOG.md << EOF
        ## Changes

        ${CHANGELOG}

        ## Docker Images

        - \`docker pull thsrite/ytb-dl:${GITHUB_REF#refs/tags/}\`
        - \`docker pull thsrite/ytb-dl:latest\`

        ## Quick Start

        \`\`\`bash
        # Using docker-compose
        curl -O https://raw.githubusercontent.com/thsrite/ytb-dl/${GITHUB_REF#refs/tags/}/docker-compose.yml
        docker-compose up -d

        # Or using docker directly
        docker run -p 8000:8000 -v ./downloads:/app/downloads -v ./config:/app/config thsrite/ytb-dl:${GITHUB_REF#refs/tags/}
        \`\`\`
        EOF

        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        cat CHANGELOG.md >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: false